baseURL = "https://mjlile.com/"
languageCode = "en-us"
title = "Matthew Lile"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright, Matthew Lile"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	subtitle = "Computer science student at the University of Michigan"

	# Optional 64x64 avatar image.
	avatar = "https://avatars2.githubusercontent.com/u/15596064?s=460&u=50c2e71abd5904d685f3058b35e3ad9764c3b6e6&v=4"
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mjlile"

[taxonomies]
   tag = "tags"
